set(QCODEEDIT_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/ext/qcodeedit/lib)
set(QCODEEDIT_LIBRARY qcodeedit)

set(QCODEEDIT_FOUND True)

if (QCODEEDIT_FOUND)
  set(QCODEEDIT_INCLUDE_DIR ${QCODEEDIT_INCLUDE_DIR} ${QCODEEDIT_INCLUDE_DIR}/document ${QCODEEDIT_INCLUDE_DIR}/language ${QCODEEDIT_INCLUDE_DIR}/qnfa ${QCODEEDIT_INCLUDE_DIR}/widgets)
endif (QCODEEDIT_FOUND)

mark_as_advanced(QCODEEDIT_INCLUDE_DIR)
mark_as_advanced(QCODEEDIT_LIBRARY)

