set(QT_USE_QTNETWORK TRUE)

set(UNIQUE_APPPLICATION_PATH ${CMAKE_SOURCE_DIR}/ext/qtsingleapplication/src)

include_directories(${UNIQUE_APPPLICATION_PATH})

set(UNIQUE_APPPLICATION_SOURCES ${UNIQUE_APPPLICATION_PATH}/qtsingleapplication.cpp ${UNIQUE_APPPLICATION_PATH}/qtlocalpeer.cpp)
set(UNIQUE_APPPLICATION_HEADERS ${UNIQUE_APPPLICATION_PATH}/qtsingleapplication.h ${UNIQUE_APPPLICATION_PATH}/qtlocalpeer.h)
