CONFIG += release
unix {
    QMAKE_LFLAGS = -rdynamic
}

CONFIG(release, debug|release) {
	DEFINES += _XINX_RELEASE_MODE_
}

MOC_DIR = .
OBJECTS_DIR = .
RCC_DIR = .

QMAKE_CXXFLAGS_RELEASE = "-Os"

VERSION_MAJOR = 0
VERSION_MINOR = 9
VERSION_RELEASE = 0
DEFINES += VERSION_MAJOR=$$VERSION_MAJOR VERSION_MINOR=$$VERSION_MINOR VERSION_RELEASE=$$VERSION_RELEASE

#PRECOMPILED_HEADER = stable_header.h
