// This file is auto-generated file, don't modify it unless you want to lose your code
// Generated by qgenconfig v0.1 (c) Ulrich Van Den Hekke

#ifndef _GCESETTINGS_H_
#define _GCESETTINGS_H_
#pragma once

#include <QSettings>

class PrivateGceSettings;

class GceSettingsSettings : public QSettings
{
public:
	GceSettingsSettings(const QString & organization, const QString & application);
	void setValue(const QString & key, const QVariant & value, const QVariant & defaultValue);
	void setValue(const QString & key, const QVariant & value);
};

class GceSettings
{
public:
	struct struct_globals
	{
		bool readConfigurations;
		bool readDictionaries;
	};


	GceSettings(const GceSettings & origine);
	GceSettings();
	virtual ~GceSettings();

	virtual void setDefault();
	virtual void load();
	virtual void save();

	struct_globals & config();

	GceSettings& operator=(const GceSettings& p);
protected:
	virtual struct_globals getDefaultGlobals();
	virtual GceSettings::struct_globals getSettingsGlobals(GceSettingsSettings * settings, const QString & path, const GceSettings::struct_globals & defaultValue);
	virtual void setSettingsGlobals(GceSettingsSettings * settings, const QString & path, const GceSettings::struct_globals & value);

private:
	PrivateGceSettings * d;
	friend class PrivateGceSettings;
};
#endif // _GCESETTINGS_H_

