#define VERSION_MAJOR     0
#define VERSION_MINOR     9
#define VERSION_RELEASE   1
#define VERSION_BUILD     0

#define str(s) #s
#define xstr(s) str(s)

#define FILEVER    VERSION_MAJOR , VERSION_MINOR , VERSION_RELEASE , VERSION_BUILD
#define PRODUCTVER VERSION_MAJOR , VERSION_MINOR , VERSION_RELEASE , VERSION_BUILD
#define STRFILEVER    xstr(VERSION_MAJOR) "," xstr(VERSION_MINOR) "," xstr(VERSION_RELEASE) "," xstr(VERSION_BUILD) "\0"
#define STRPRODUCTVER xstr(VERSION_MAJOR) "," xstr(VERSION_MINOR) "," xstr(VERSION_RELEASE) "," xstr(VERSION_BUILD) "\0"

#define VERSION_STRING "v" xstr(VERSION_MAJOR) "." xstr(VERSION_MINOR) "." xstr(VERSION_RELEASE)
#define LONG_VERSION_STRING "v" xstr(VERSION_MAJOR) "." xstr(VERSION_MINOR) "." xstr(VERSION_RELEASE) "." xstr(VERSION_BUILD)

