# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./demo1
# Target is an application:  


IDEALITY_DIR = ../lib 

include($$IDEALITY_DIR/ideality.pri)

CONFIG += release \
          warn_on 
TEMPLATE = app 
SOURCES += demo2.cpp 
