# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./demo3
# Target is an application:  

HEADERS += mainwindow.h 
SOURCES += mainwindow.cpp \
           main.cpp 
KDEV_QTVER = 4
IDEALITY_DIR = ../lib
include($$IDEALITY_DIR/ideality.pri)

CONFIG += release \
warn_on
TEMPLATE = app
RESOURCES = dockwidgets.qrc
