# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./demo1
# Target is an application:  

KDEV_QTVER = 4 

IDEALITY_DIR = ../lib
include($$IDEALITY_DIR/ideality.pri)

CONFIG += release \
          warn_on 
TEMPLATE = app 
SOURCES += demo1.cpp 


