#!/bin/sh
LD_LIBRARY_PATH=../framework:../components:../ext/qcodeedit:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH
# Test au format xml
xvfb-run ./testxinxcodeedit -xml > unittest.xml
sleep 1
xvfb-run ./testcontentview -xml > unittest2.xml
sleep 1
xvfb-run ./testsnipets -xml > unittest3.xml
sleep 1
xvfb-run ./testutils -xml > unittest4.xml
sleep 1
# Test au format log
xvfb-run ./testxinxcodeedit
sleep 1
xvfb-run ./testcontentview
sleep 1
xvfb-run ./testsnipets
sleep 1
xvfb-run ./testutils
