#!/bin/sh

cd ../framework
for filename in `ls *.gcda *.gcno *.o` ; do
	src_filename=`find -name ${filename%.*}.cpp`
	src_directory=`dirname $src_filename`

	if [ $src_directory != "." ] ; then 
		cp -l $filename $src_directory/
	fi
done