// This file is auto-generated file, don't modify it unless you want to lose your code
// Generated by qgenconfig v0.1 (c) Ulrich Van Den Hekke

#ifndef _PLUGINSETTINGS_H_
#define _PLUGINSETTINGS_H_

#include <QSettings>
#include <QString>

class PrivatePluginSettings;

class PluginSettings {
public:
	struct struct_globals {
		QString progressMessages;
		int compressionLevel;
		bool pruneEmptyDirectories;
		bool createDirectories;
		bool createChangelog;
	};


	PluginSettings( const PluginSettings & origine );
	PluginSettings();
	virtual ~PluginSettings();

	virtual void setDefault();
	virtual void load();
	virtual void save();

	struct_globals & config();

	PluginSettings& operator=(const PluginSettings& p);
protected:
	virtual struct_globals getDefaultGlobals();
	virtual struct_globals getSettingsGlobals( QSettings * settings, const QString & path, struct_globals defaultValue );
	virtual void setSettingsGlobals( QSettings * settings, const QString & path, struct_globals value );

private:
	PrivatePluginSettings * d;
	friend class PrivatePluginSettings;
};
#endif // _PLUGINSETTINGS_H_

