######################################################################
# Automatically generated by qmake (2.01a) jeu. juin 14 17:19:53 2007
######################################################################

TEMPLATE = app
TARGET = qnfa
DEPENDPATH += .
INCLUDEPATH += . .. ../document ../language

QT += xml

# Input
HEADERS += qnfa.h
SOURCES += qnfa.cpp main.cpp

HEADERS += ../qformatfactory.h
SOURCES += ../qformatfactory.cpp

