# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

SUBDIRS += lib \
           demo1 \
           demo2 \
           demo3 \
           demo4 \
           demo5 \
           demo6 
KDEV_QTVER = 4
CONFIG += release \
warn_on
TEMPLATE = subdirs
