/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -a studioadaptor com.generix.xmlstudio.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef STUDIOADAPTOR_H_1168087321
#define STUDIOADAPTOR_H_1168087321

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.generix.xmlstudio
 */
class XmlstudioAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.generix.xmlstudio")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.generix.xmlstudio\" >\n"
"    <signal name=\"open\" >\n"
"      <arg direction=\"out\" type=\"s\" name=\"fileName\" />\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    XmlstudioAdaptor(QObject *parent);
    virtual ~XmlstudioAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void open(const QString &fileName);
};

#endif
