/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -a studioadaptor com.generix.xinx.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef STUDIOADAPTOR_H_1186387089
#define STUDIOADAPTOR_H_1186387089

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.generix.xinx
 */
class XinxAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.generix.xinx")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.generix.xinx\" >\n"
"    <method name=\"newFile\" />\n"
"    <method name=\"openFile\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"filename\" />\n"
"    </method>\n"
"    <method name=\"saveAllFile\" />\n"
"    <method name=\"closeAllFile\" />\n"
"    <method name=\"openProject\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"filename\" />\n"
"    </method>\n"
"    <method name=\"closeProject\" />\n"
"  </interface>\n"
        "")
public:
    XinxAdaptor(QObject *parent);
    virtual ~XinxAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void closeAllFile();
    void closeProject();
    void newFile();
    void openFile(const QString &filename);
    void openProject(const QString &filename);
    void saveAllFile();
Q_SIGNALS: // SIGNALS
};

#endif
