/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -a studioadaptor com.editor.xinx.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef STUDIOADAPTOR_H_1188293920
#define STUDIOADAPTOR_H_1188293920

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.editor.xinx
 */
class XinxAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.editor.xinx")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.editor.xinx\" >\n"
"    <method name=\"newStylesheetFile\" />\n"
"    <method name=\"newXmlDataFile\" />\n"
"    <method name=\"newJavascriptFile\" />\n"
"    <method name=\"newWebservicesFile\" />\n"
"    <method name=\"newTemplate\" />\n"
"    <method name=\"newDefaultFile\" />\n"
"    <method name=\"openFile\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"filename\" />\n"
"    </method>\n"
"    <method name=\"saveFileAs\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"filename\" />\n"
"    </method>\n"
"    <method name=\"saveAllFile\" />\n"
"    <method name=\"closeFile\" />\n"
"    <method name=\"closeAllFile\" />\n"
"    <method name=\"newProject\" />\n"
"    <method name=\"openProject\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"filename\" />\n"
"    </method>\n"
"    <method name=\"closeProjectNoSessionData\" />\n"
"    <method name=\"closeProjectWithSessionData\" />\n"
"    <method name=\"callWebservices\" />\n"
"    <method name=\"updateWebServicesList\" />\n"
"  </interface>\n"
        "")
public:
    XinxAdaptor(QObject *parent);
    virtual ~XinxAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void callWebservices();
    void closeAllFile();
    void closeFile();
    void closeProjectNoSessionData();
    void closeProjectWithSessionData();
    void newDefaultFile();
    void newJavascriptFile();
    void newProject();
    void newStylesheetFile();
    void newTemplate();
    void newWebservicesFile();
    void newXmlDataFile();
    void openFile(const QString &filename);
    void openProject(const QString &filename);
    void saveAllFile();
    void saveFileAs(const QString &filename);
    void updateWebServicesList();
Q_SIGNALS: // SIGNALS
};

#endif
