/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -a studioadaptor com.editor.xinx.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "studioadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class XinxAdaptor
 */

XinxAdaptor::XinxAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

XinxAdaptor::~XinxAdaptor()
{
    // destructor
}

void XinxAdaptor::closeAllFile()
{
    // handle method call com.editor.xinx.closeAllFile
    QMetaObject::invokeMethod(parent(), "closeAllFile");
}

void XinxAdaptor::closeProject()
{
    // handle method call com.editor.xinx.closeProject
    QMetaObject::invokeMethod(parent(), "closeProject");
}

void XinxAdaptor::newFile()
{
    // handle method call com.editor.xinx.newFile
    QMetaObject::invokeMethod(parent(), "newFile");
}

void XinxAdaptor::openFile(const QString &filename)
{
    // handle method call com.editor.xinx.openFile
    QMetaObject::invokeMethod(parent(), "openFile", Q_ARG(QString, filename));
}

void XinxAdaptor::openProject(const QString &filename)
{
    // handle method call com.editor.xinx.openProject
    QMetaObject::invokeMethod(parent(), "openProject", Q_ARG(QString, filename));
}

void XinxAdaptor::saveAllFile()
{
    // handle method call com.editor.xinx.saveAllFile
    QMetaObject::invokeMethod(parent(), "saveAllFile");
}

