# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./demo4
# Target is an application:  

HEADERS += mainwindow.h 
SOURCES += demo4.cpp \
           mainwindow.cpp 
KDEV_QTVER = 4

IDEALITY_DIR = ../lib
include($$IDEALITY_DIR/ideality.pri)

CONFIG += release \
warn_on
TEMPLATE = app
